name: Update Vector Index

on:
  push:
    branches: [main]

jobs:
  index:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run parser tests
        run: poetry run pytest tests --maxfail=1 --disable-warnings -v

      - name: Run CodeDoc-AI indexing (auto-detect all languages)
        run: poetry run codedoc-ai index .

      - name: Generate documentation (output to docs/generated)
        run: poetry run codedoc-ai generate . --out docs/generated/

      - name: Upload generated docs
        uses: actions/upload-artifact@v4
        with:
          name: generated-docs
          path: docs/generated/
